<?php

return [
    'api_url' => env('WRECKFEST_API_URL', 'https://localhost:5101/api'),
    'ws_url' => env('WRECKFEST_WS_URL', 'wss://localhost:5101/ws'),
    'ocr_enabled' => env('WRECKFEST_OCR_ENABLED', false),

    // AI model for track collection assistant
    // Options: gpt-4o, gpt-4o-mini, gpt-4-turbo, gpt-3.5-turbo
    'ai_model' => env('WRECKFEST_AI_MODEL', 'gpt-4o-mini'),

    // AI response mode: uses async job + polling to avoid PHP timeout issues
    'ai_async' => env('WRECKFEST_AI_ASYNC', true),

    // Brand colors used across the application (both frontend and admin panel)
    'brand' => [
        'primary' => '#a03d00',
    ],

    // Track data has been moved to database/seeders/TrackSeeder.php

    'gamemodes' => [
        'racing' => 'Racing',
        'derby' => 'Last Man Standing',
        'derby deathmatch' => 'Deathmatch',
        'team derby' => 'Team Deathmatch',
        'team race' => 'Team Race',
        'elimination race' => 'Elimination Race',
    ],

    // Gamemode categories for track compatibility
    'derby_gamemodes' => [
        'derby',
        'derby deathmatch',
        'team derby',
    ],

    'racing_gamemodes' => [
        'racing',
        'team race',
        'elimination race',
    ],

    // Tracks that are only compatible with derby gamemodes (demolition arenas)
    'derby_only_tracks' => [
        'bigstadium_demolition_arena',
        'crm01_3',
        'field_derby_arena',
        'fields11_1',
        'fields13_2',
        'grass_arena_demolition_arena',
        'mudpit_demolition_arena',
        'smallstadium_demolition_arena',
        'speedway2_classic_arena',
        'speedway2_demolition_arena',
        'triangle_r2',
        'urban07',
        'urban09_2',
    ],

    'grid_orders' => [
        'perf_normal' => 'Performance Normal',
        'perf_reverse' => 'Performance Reverse',
        'random' => 'Random',
        'qualifying' => 'Qualifying',
        'cup_normal' => 'Cup Normal',
        'cup_reverse' => 'Cup Reverse',
    ],

    'session_modes' => [
        'normal' => 'Normal Session (no qualifying, no Cup Points)',
        'qualify-sprint' => 'Qualifying Sprint (race winner gets Pole Position)',
        'qualify-lap' => 'Qualifying Lap (Best Lap gets Pole Position)',
        '30p-aggr' => '30P Aggressive (Winner = 30, 27, 25, 23, 20...)',
        '25p-aggr' => '25P Aggressive (Winner = 25, 18, 15, 12, 10, 8, 6, 4, 2, 1)',
        '25p-mod' => '25P Moderate (Winner = 25, 20, 16, 11...)',
        '24p-lin' => '24P Linear (Winner = 24, then -1 per position)',
        '16p-lin' => '16P Linear (Winner = 16, then -1 per position)',
        '10p-double' => '10P Double (Winner = 20, then -2 per position)',
        '10p-lin' => '10P Linear (Winner = 10, then -1 per position)',
        '35p-folk' => '35P Folk Race (Winner = 35, 30, 25, 20, 18, 16...)',
        'f1-1991' => 'F1 1991 (Winner = 10, 6, 4, 3, 2, 1)',
        'f1-2003' => 'F1 2003 (Winner = 10, 8, 6, 5, 4, 3, 2, 1)',
        'f1-2010' => 'F1 2010 (Winner = 25, 18, 15, 12, 10, 8, 6, 4, 2, 1)',
        'player_count_1' => 'Player Count 1 (Winner = player count, then -1 per position)',
    ],

    'weather_conditions' => [
        'clear' => 'Clear',
        'overcast' => 'Overcast',
        'rain' => 'Rain',
        'storm' => 'Storm',
        'fog' => 'Fog',
        'random' => 'Random',
    ],

    'frequencies' => [
        'low' => 'Low (20 Hz)',
        'high' => 'High (30-60 Hz)',
    ],

    'ai_difficulties' => [
        'novice' => 'Novice',
        'amateur' => 'Amateur',
        'expert' => 'Expert',
    ],

    'vehicle_damages' => [
        'normal' => 'Normal',
        'intense' => 'Intense',
        'realistic' => 'Realistic',
        'extreme' => 'Extreme',
    ],

    'car_classes' => [
        'a' => 'Class A',
        'b' => 'Class B',
        'c' => 'Class C',
        'd' => 'Class D',
        'all' => 'All Classes',
    ],

    'cars' => [
        'bandit' => 'Bandit',
        'bandit ripper v8' => 'Bandit Ripper V8',
        'battle bus' => 'Battle Bus',
        'big rig' => 'Big Rig',
        'blade' => 'Blade',
        'boomer' => 'Boomer',
        'boomer (f)' => 'Boomer (F)',
        'boomer (l)' => 'Boomer (L)',
        'boomer (lr)' => 'Boomer (LR)',
        'boomer rs' => 'Boomer RS',
        'boomer rs (l)' => 'Boomer RS (L)',
        'boomer rs (rt)' => 'Boomer RS (RT)',
        'buggy' => 'Buggy',
        'buggy (f)' => 'Buggy (F)',
        'buggy (l)' => 'Buggy (L)',
        'bugzilla' => 'Bugzilla',
        'bulldog' => 'Bulldog',
        'bullet' => 'Bullet',
        'bumper car' => 'Bumper Car',
        'bumper car (tl)' => 'Bumper Car (TL)',
        'car>dinal' => 'Car>dinal',
        'dominator' => 'Dominator',
        'dominator (b)' => 'Dominator (B)',
        'dominator (l)' => 'Dominator (L)',
        'dominator (tl)' => 'Dominator (TL)',
        'doom rig' => 'Doom Rig',
        'doom rig (tl)' => 'Doom Rig (TL)',
        'double decker' => 'Double Decker',
        'double decker (l)' => 'Double Decker (L)',
        'dragslayer' => 'Dragslayer',
        'dragslayer (l)' => 'Dragslayer (L)',
        'eagle r' => 'Eagle R',
        'el matador' => 'El Matador',
        'el matador (l)' => 'El Matador (L)',
        'firefly' => 'Firefly',
        'firefly (f)' => 'Firefly (F)',
        'firefly (tl)' => 'Firefly (TL)',
        'gatecrasher' => 'Gatecrasher',
        'gorbie' => 'Gorbie',
        'gorbie (l)' => 'Gorbie (L)',
        'grand duke' => 'Grand Duke',
        'gremlin' => 'Gremlin',
        'gremlin (l)' => 'Gremlin (L)',
        'gremlin (tl)' => 'Gremlin (TL)',
        'hammerhead' => 'Hammerhead',
        'hammerhead (f)' => 'Hammerhead (F)',
        'hammerhead (l)' => 'Hammerhead (L)',
        'hammerhead rs' => 'Hammerhead RS',
        'harvester' => 'Harvester',
        'hearse' => 'Hearse',
        'hellvester' => 'Hellvester',
        'honey pot' => 'Honey Pot',
        'hornet' => 'Hornet',
        'hornet (f)' => 'Hornet (F)',
        'hornet (tl)' => 'Hornet (TL)',
        'hotbomb' => 'Hotbomb',
        'hotshot' => 'Hotshot',
        'hotshot (l)' => 'Hotshot (L)',
        'hunter panther' => 'Hunter Panther',
        'killerbee' => 'Killerbee',
        'killerbee (f)' => 'Killerbee (F)',
        'killerbee (l)' => 'Killerbee (L)',
        'killerbee (tl)' => 'Killerbee (TL)',
        'killerbee s' => 'Killerbee S',
        'killerbee s (l)' => 'Killerbee S (L)',
        'killerpig' => 'Killerpig',
        'killerpig (tl)' => 'Killerpig (TL)',
        'lawn mower' => 'Lawn Mower',
        'lawn mower (l)' => 'Lawn Mower (L)',
        'lawn mower (tl)' => 'Lawn Mower (TL)',
        'limo' => 'Limo',
        'limo (l)' => 'Limo (L)',
        'little thrasher' => 'Little Thrasher',
        'motorhome' => 'Motorhome',
        'motorhome (l)' => 'Motorhome (L)',
        'motorhome (tl)' => 'Motorhome (TL)',
        'muddigger' => 'Muddigger',
        'nexus rx' => 'Nexus RX',
        'nexus rx (l)' => 'Nexus RX (L)',
        'nexus rx (rl)' => 'Nexus RX (RL)',
        'outlaw' => 'Outlaw',
        'panther rs' => 'Panther RS',
        'panther rs (b)' => 'Panther RS (B)',
        'pocket rocket' => 'Pocket Rocket',
        'pocket rocket (tl)' => 'Pocket Rocket (TL)',
        'raiden rs' => 'Raiden RS',
        'rammer' => 'Rammer',
        'rammer (l)' => 'Rammer (L)',
        'rammer rs' => 'Rammer RS',
        'rammer rs (l)' => 'Rammer RS (L)',
        'rammer rs (tl)' => 'Rammer RS (TL)',
        'raven' => 'Raven',
        'razor' => 'Razor',
        'rebelrat' => 'Rebelrat',
        'rebelrat (tl)' => 'Rebelrat (TL)',
        'roadcutter' => 'Roadcutter',
        'roadcutter (l)' => 'Roadcutter (L)',
        'roadcutter (tld)' => 'Roadcutter (TLD)',
        'roadslayer' => 'Roadslayer',
        'roadslayer (l)' => 'Roadslayer (L)',
        'roadslayer gt' => 'Roadslayer GT',
        'roadslayer gt (l)' => 'Roadslayer GT (L)',
        'roadslayer gt (tl)' => 'Roadslayer GT (TL)',
        'rocket' => 'Rocket',
        'rocket (l)' => 'Rocket (L)',
        'rocket rx' => 'Rocket RX',
        'sandstorm' => 'Sandstorm',
        'school bus' => 'School Bus',
        'school bus (l)' => 'School Bus (L)',
        'school bus (tl)' => 'School Bus (TL)',
        'sofa car' => 'Sofa Car',
        'sofa car (l)' => 'Sofa Car (L)',
        'sofa car (tl)' => 'Sofa Car (TL)',
        'speedbird' => 'Speedbird',
        'speedbird (l)' => 'Speedbird (L)',
        'speedbird gt' => 'Speedbird GT',
        'speedemon' => 'Speedemon',
        'speedie' => 'Speedie',
        'starbeast' => 'Starbeast',
        'starbeast (l)' => 'Starbeast (L)',
        'starbeast (lr)' => 'Starbeast (LR)',
        'starbeast (tl)' => 'Starbeast (TL)',
        'starbeast ss' => 'Starbeast SS',
        'stellar' => 'Stellar',
        'stellar (l)' => 'Stellar (L)',
        'step van' => 'Step Van',
        'stock car' => 'Stock Car',
        'sunrise super' => 'Sunrise Super',
        'super venom' => 'Super Venom',
        'supervan' => 'Supervan',
        'supervan (l)' => 'Supervan (L)',
        'supervan (tl)' => 'Supervan (TL)',
        'sweeper' => 'Sweeper',
        'sweeper (b)' => 'Sweeper (B)',
        'sweeper (f)' => 'Sweeper (F)',
        'tristar' => 'Tristar',
        'tristar (b)' => 'Tristar (B)',
        'tristar (tl)' => 'Tristar (TL)',
        'trooper' => 'Trooper',
        'trophy runner' => 'Trophy Runner',
        'vandal' => 'Vandal',
        'venom' => 'Venom',
        'wardigger' => 'Wardigger',
        'warwagon' => 'Warwagon',
        'warwagon (dtl)' => 'Warwagon (DTL)',
        'warwagon (l)' => 'Warwagon (L)',
        'warwagon (tl)' => 'Warwagon (TL)',
        'wildking' => 'Wildking',
        'wingman' => 'Wingman',
    ],
];
